### ISSUE TITLE
ChatGPT client for all platforms and OpenAI library for Delphi

### ISSUE THREAD

**Issue by HemulGM** [awesome-chatgpt/awesome-chatgpt#114]
https://github.com/HemulGM/DelphiOpenAI
https://github.com/HemulGM/ChatGPT

**Comment by edison1105** [comment]
thanks! close via 5b4e86cefe0b9050d776582558a164926a0dd566 and 826a7e8c3918dd8cefcd191982cd37ccea0e4867
