### ISSUE TITLE
ChatGPT Plus Meets Shell

### ISSUE THREAD

**Issue by VolkanSah** [awesome-chatgpt/awesome-chatgpt#131]
Powerfull Plugin for developers:
you can use the power of you unix/linux terminal in ChatGPT Plus GPT 4 for free ;)
https://github.com/VolkanSah/ChatGPT-ShellMaster
Security-Best-Practices for your own GPT scripts:
https://github.com/VolkanSah/ChatGPT-Security-Best-Practices
have some other GPT Stuff  ;)

**Comment by edison1105** [comment]
closed via https://github.com/awesome-chatgpt/awesome-chatgpt/commit/d541566a2a616d11dea87464403148fc4cfc6b2d
