### ISSUE TITLE
Add Ultimate ChatGPT in list

### ISSUE THREAD

**Issue by imabutahersiddik** [awesome-chatgpt/awesome-chatgpt#136]
**Website URL**

```
https://chatgpt.kiask.xyz/
```

**Website Type**

- [x] ChatGPT site
- [ ] Other

**Website Description and Usage**

> Please provide a clear description to help others understand how to use it.

- [x] 😄 Free to use (open and ready to use with no restrictions)
- [ ] 🔑 Free to use, but requires login or password
- [ ] 🤑 Paid service
- [ ] 🎁 Paid service with a trial period

**Website Icon - Path (optional)**
> Square-shaped icon

```
For example: https://chatgpt.kiask.xyz/android-chrome-512x512.png
```

**Requires International Access (optional)**

- [x] No
- [ ] Yes

**Comment by edison1105** [comment]
close via https://github.com/awesome-chatgpt/awesome-chatgpt/commit/72df51f9468fdf38b69682c8b7e77b8244477108
