### ISSUE TITLE
Suggestion to use descriptive commits

### ISSUE THREAD

**Issue by dandv** [awesome-chatgpt/awesome-chatgpt#28]
"Update README.md" could be more precise :pray: 

![image](https://user-images.githubusercontent.com/33569/228403319-e4f10e08-d6f5-4e4e-99d8-d4cde5eb20b8.png)

**Comment by edison1105** [comment]
@dandv 
I invited you to become a member. 
check your e-mail if you are ready.

**Comment by dandv** [comment]
Joined, thank you!
